### PR TITLE
Fix Android HTTPS connections

### LINKED ISSUE #71: Cabin can’t get any info from my cluster
I saw the green light that indicates it’s running, but none of the tabs (pods, etc.) show any data, just the loading indicator.

3fdbe455-7912-4eae-95e2-321f611aac90

I’m not quite sure how to get logs from the Kubernetes cluster to see if there’s an authentication error. I didn’t enter a username and password because there isn’t one, as far as I know (just a self signed CA and a token, which I got from the config that kubeadm generates)

Here’s a snippet describing how I set up my cluster: https://gitlab.com/snippets/1674542

So in Cabin, I put https://192.168.1.22:6443/ and pasted the CA and token from the admin.conf that was generated after running kubeadm

Is that the right way to set it up?

### PR DESCRIPTION
**Pull request by kemcake**
Fix android communication with cluster

ReactNative team introduced a stupid breaking change without notifying anyone [here](https://github.com/facebook/react-native/commit/0a71f48b1349ed09bcb6e76ba9ff8eb388518b15), this means we have to use `patch-package` to fix it

Todo:
- [x] Fix https self signed certificate acceptance
- [x] Fix cluster authentication by certificate

This PR should fix #71 #70 #4 (and potentially other issues)

### CODE REVIEW

**Comment by kemcake** [comment]
Well, managed to refactor and fix things, tested on a GKE cluster and a Minikube.

screenshot 2017-09-19 13 27 15

**Comment by ftab** [comment]
Will this make it into iOS, too, or is it broke in some other way over there?

**Comment by kemcake** [comment]
iOS works fine (and always did) for these cases, @ftab you have any issu with iOS?

**Comment by ftab** [comment]
Yes, I'm using iOS in #71

**Pull request merged**
