### PR TITLE
Improve Get Started

### PR DESCRIPTION
**Pull request by kemcake**
Fix issues with dependencies when starting the project from scratch.
Update the readme with the RN get started guide

Related to #66

### CODE REVIEW

**Comment by sebgoa** [comment]
@vtuson you want to pull this PR and give it a go ?

**Comment by vtuson** [comment]
I compiles more cleanly now, still complains about a missing .env file.

However It still fails at run with:
Loading dependency graph, done.
Bundling `index.android.js`  [development, non-minified, hmr disabled]  0.0% (3/324), failed.
error: bundling failed: "Unable to resolve module `../node_modules/react-native/src/utils/LocalesUtils` from `/Users/victorpalau/cabin/src/config.js`: could not resolve `/Users/victorpalau/cabin/node_modules/react-native/src/utils/LocalesUtils' as a file nor as a folder"

**Comment by kemcake** [comment]
The .env file is not necessary, it is used for the google api client ID or to setup production environment. Used in `src.config.js`
For the import issue, I can't reproduce, but I just pushed a commit to use relative path instead of using aliases in `config.js`, it should fix it...

**Comment by vtuson** [comment]
I have been able to get the app running in the emulator with the latest fix.

Without an .env file I cant configure my own google client ID and I can not test a problem that I am phasing with GKE authentication. I will open a separate issue for this.

**Comment by vtuson** [comment]
ok so I am having the same problem that described in issue #4 

I have commented in it. I will be happy to debug it if you share the format of the .env file - that way I could setup a Google project id of my own.

**Comment by kemcake** [comment]
@vtuson the .env file only contains this:

```
GOOGLE_CLIENT_ID=xxxxxxxxxxx.apps.googleusercontent.com
```

And yes I'm working on #4, I found the issue, this is an undocumented breaking changes introduces in react native 0.46

**Comment by vtuson** [comment]
Hi,

Thanks I got it working by looking at the code. I think it is worth pointing out that you will need your google project (Android oauth) to have enabled:
Google Cloud Resource Manager API
Google Container Engine API

and that container engine requires billing to be setup. 

Thanks

Victor

**Pull request merged**
